---
- name: Mettre à jour le cache APT
  apt:
    update_cache: yes

- name: Installer kubelet, kubeadm et kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Installer nfs-common sur tous les nœuds
  apt:
    name: nfs-common
    state: present
