- name: Installer les paquets NFS
  apt:
    name:
      - nfs-kernel-server
    state: present
    update_cache: yes

- name: Installer les paquets NFS côté client
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Créer le dossier à exporter
  file:
    path: "{{ nfs_export_dir }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Configurer l'export NFS
  template:
    src: exports.j2
    dest: /etc/exports
    mode: '0644'
  notify: Restart NFS

- name: Activer et démarrer le service NFS
  systemd:
    name: nfs-server
    enabled: yes
    state: started
